name: rdd
version: '1.0-SNAPSHOT'
main: sh.smnx.rdd.Rdd
commands:
  rdd:
    description: Jouer a la roue du destin
    usage: /<command> <player>
    permission: rdd.rdd_command
  rdd-list:
    description: Lister les prix de la roue du destin
    usage: /<command>
    permission: rdd.rdd_command